# AGGREGATE FUNCTION

#TOTAL   ---- SUM()
#MAXIMUM ---- MAX()
#MINIMUM ---- MIN()
#COUNT   ---- COUNT()
#AVERAGE ---- AVG()
#INTEGER ---- ROUND()
#UNIQUE  ---- DISTINCT()

select * from sales;

SELECT MAX(QUANTITY) FROM SALES;

SELECT MIN(QUANTITY) FROM SALES;

SELECT SUM(QUANTITY) FROM SALES;

SELECT AVG(QUANTITY) FROM SALES;

SELECT COUNT(*) FROM SALES;

SELECT * FROM SALES WHERE LOCATION = "DELHI";

SELECT count(LOCATION) FROM SALES WHERE LOCATION = "DELHI";

SELECT distinct(CATAGORIES) FROM SALES;

SELECT COUNT(distinct(CATAGORIES)) FROM SALES;