/* 
CASE EXPERSSION
____IS LIKE IF ELSE___

 ORDER WHOSE PRICE IS CATEGORISED AS FOLLOWING CASES ASSIGN STATUS TO THEM
PRICE IS GREATER THAN EQUAL TO 60K --> HIGH COST PRODUCT
PRICE RANGEING FROM 30K - 50K --> AFFORDABLE COST PRODUCTS
PRICE LESS THEN 30K --> LOW COST PRODUCTS */

SELECT *,
CASE WHEN PRICE >=60000
THEN "HIGH COST"
WHEN PRICE >= 30000 AND PRICE <= 50000
THEN "AFFORDABLE COST"
ELSE "LOW COST"
END AS PRODUCT_PRICE_STATUS
FROM SALES;
SELECT * FROM SALES;

