use week;

/* 
# CONSTRAINTS ----> RESTRICTION OR LIMITATION
 __________USE BEFORE CREATING TABLE_________
 
1. UNIQUE --> IT HELPS YOU TO ENTER UNIQUE ENTRIES IN YOUR DATA.
2. NOT NULL --> TO AVOID BLANK CELLS OR NULL VALUES IN YOUR DATA.
3. DEFAULT --> IT WILL HELP YOU TO PUT DEFAULT VALUE IN BLANK CELL.
4. CHECK --> IN THIS YOU WILL GIVE CERTAIN CONDITION, WHENEVER THE GIVEN CONDITION GET FULFILLED THEN ONLY DATA GETS ENTERED. 
5. PRIMARY KEY --> CONTAIN UNIQUE AND NOT NULL 
6. FORIEGN KEY --> HELPS TO JOIN ONE TABLE TO ANOTHER 
7. ENUM --> IN THIS YOU PASS CERTAIN VALUES. (M,F,O) */

# HOW TO USE CONSTRAINTS IN YOUR TABLE

CREATE TABLE EMPLOYEE(
ID INT auto_increment PRIMARY KEY,
NAME VARCHAR(255) NOT NULL,
DEPARTMENT VARCHAR(255) DEFAULT "SOON TO BE ASSIGNED",
AGE INT CHECK (AGE>=18 AND AGE <=60),
GENDER ENUM ('MALE','FEMALE','OTHERS'),
EMAIL_ID VARCHAR(255) unique);

INSERT INTO EMPLOYEE(ID,NAME,DEPARTMENT,AGE,GENDER,EMAIL_ID)
VALUES(007,"ROB","IT",24,'MALE','ROB@GMAIL.COM');

SELECT * FROM EMPLOYEE;

INSERT INTO EMPLOYEE(ID,NAME,DEPARTMENT,AGE,GENDER,EMAIL_ID)
VALUES(555,"VIV","IT",28,'MALE','VIV@GMAIL.COM');



