use week;
CREATE TABLE SALES(
ORDER_ID INT,
CUSTOMER_NAME VARCHAR(255),
CUSTOMER_ID INT,
PRODUCT VARCHAR(255),
GENDER VARCHAR(255),
CATAGORIES VARCHAR(255),
DOO DATE,
PRICE INT,
QUANTITY INT,
LOCATION varchar(255));

select * from SALES
