use week;

#      QUERY

select * from Sales;

SELECT MAX(PRICE) FROM SALES;
SELECT * FROM SALES WHERE PRICE = 25085000;

SELECT AVG(PRICE) FROM SALES;
SELECT * FROM SALES WHERE PRICE >= 45081.2199;

SELECT AVG(PRICE) FROM SALES WHERE LOCATION = "DELHI";
SELECT * FROM SALES WHERE PRICE > (SELECT AVG(PRICE) FROM SALES WHERE LOCATION = "DELHI");

SELECT * FROM SALES WHERE LOCATION ="DELHI" AND PRICE >= (SELECT AVG(PRICE) FROM SALES);




#                   SUB QUERY AND NESTED QUERY

SELECT * FROM SALES WHERE PRICE = (SELECT MAX(PRICE) FROM SALES);
SELECT * FROM SALES WHERE PRICE >= (SELECT AVG(PRICE) FROM SALES);

SELECT * FROM SALES WHERE CATAGORIES = "ELECTRONICS" AND LOCATION = "MUMBAI" AND QUANTITY >80; 
SELECT * FROM SALES WHERE PRICE > (SELECT MAX(PRICE) FROM  SALES WHERE CATAGORIES = "ELECTRONICS") AND LOCATION = "MUMBAI" AND QUANTITY >80;

SELECT * FROM SALES WHERE PRICE > (SELECT AVG(PRICE) FROM  SALES WHERE CATAGORIES = "CLOTHING") AND LOCATION = "MUMBAI" AND QUANTITY >80;

SELECT * FROM SALES WHERE PRICE > (SELECT AVG(PRICE) FROM SALES WHERE LOCATION = "DELHI" AND CATAGORIES = "CLOTHING") AND LOCATION = "MUMBAI" AND CATAGORIES = "ELECTRONICS";